[package]
name = "rust_grep"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex = { version = "1.11.0" }
glob = { version = "0.3.1" }
log = { version = "0.4.22" }
flexi_logger = { version = "0.29.6" }
tempfile = "3.5"
